### ISSUE TITLE
when to release the code and the model correspondingly?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [dluvizon/pose-regression#1]
hi @dluvizon,

do you have a plan when to release the code and the model?

thanks.

**Comment by dluvizon** [comment]
Hi @zimenglan-sysu-512 ,
The code and model _were expected_ to be available by the end of this week, but unfortunately I have to postpone the release.
The code will be available as soon as possible.

**Comment by mychina75** [comment]
Hi, @dluvizon,
Which platform are you using, Caffe, or torch?

**Comment by dluvizon** [comment]
Keras and TensorFlow.

**Comment by dluvizon** [comment]
Demo code and weights released.
