### ISSUE TITLE
using GPU becomes much slower

### ISSUE THREAD

**Issue by Chanbluky** [dluvizon/pose-regression#4]
Hi,  
  thanks for your great contribution. I am trying to reproduce the demo on my side, it can run about 3 frames per second, but down to 0.5 frames per second using the GPU,did you meet this issue?

thanks

**Comment by dluvizon** [comment]
For me, usually it runs at 3 fps on CPU, and slightly faster with a small low power GPU.
Actually, I suppose that the bottleneck is on acquisition / pre-processing.
